# Generated by Django 5.2.11 on 2026-02-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='core_trucks_latitud_91031a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RackPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_id', models.PositiveIntegerField(db_index=True)),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truckstop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_prices', to='core.truckstop')),
            ],
            options={
                'indexes': [models.Index(fields=['rack_id'], name='core_rackpr_rack_id_ecec6d_idx'), models.Index(fields=['retail_price'], name='core_rackpr_retail__e29c9d_idx')],
                'unique_together': {('truckstop', 'rack_id')},
            },
        ),
    ]
